/**
 * Strapi Type Definitions
 * 
 * These types define the structure of data returned from the Strapi CMS API.
 * They correspond to the content types defined in the Strapi backend.
 */

/**
 * Image format variant generated by Strapi's image processing
 */
export interface ImageFormat {
    name: string;
    hash: string;
    ext: string;
    mime: string;
    width: number;
    height: number;
    size: number;
    url: string;
}

/**
 * Strapi media image with multiple size variants
 */
export interface StrapiImage {
    id: number;
    name: string;
    alternativeText?: string;
    caption?: string;
    width: number;
    height: number;
    formats: {
        thumbnail?: ImageFormat;
        small?: ImageFormat;
        medium?: ImageFormat;
        large?: ImageFormat;
        xlarge?: ImageFormat;
    };
    url: string;
    mime: string;
    size: number;
}

/**
 * Strapi file (for PDFs and other documents)
 */
export interface StrapiFile {
    id: number;
    name: string;
    alternativeText?: string;
    caption?: string;
    width?: number;
    height?: number;
    url: string;
    mime: string;
    size: number;
}

/**
 * Meet result entry with PDF document
 */
export interface MeetResult {
    id: number;
    meetName: 'RussellCup' | 'CountyMeet' | 'AllComers';
    year: number;
    title: string;
    description?: string;
    resultsPDF: StrapiFile;
    publishedAt: string;
    createdAt: string;
    updatedAt: string;
}

/**
 * News post with featured image and rich content
 */
export interface NewsPost {
    id: number;
    title: string;
    slug: string;
    excerpt: string;
    content: string;
    featuredImage: StrapiImage;
    author?: string;
    publishedAt: string;
    createdAt: string;
    updatedAt: string;
}

/**
 * Link to static archive HTML page
 */
export interface ArchiveLink {
    id: number;
    title: string;
    url: string;
    category?: string;
    year?: number;
    publishedAt: string;
    createdAt: string;
    updatedAt: string;
}

/**
 * Homepage configuration settings
 */
export interface HomepageSettings {
    id: number;
    heroImage: StrapiImage;
    logoImage: StrapiImage;
    heroTitle: string;
    heroSubtitle: string;
    instagramEmbedCode: string;
    featuredNewsCount: number;
    createdAt: string;
    updatedAt: string;
}

/**
 * Generic Strapi API response wrapper
 */
export interface StrapiResponse<T> {
    data: T;
    meta: {
        pagination?: {
            page: number;
            pageSize: number;
            pageCount: number;
            total: number;
        };
    };
}

/**
 * Strapi error response
 */
export interface StrapiError {
    status: number;
    name: string;
    message: string;
    details?: Record<string, any>;
}
